
const countriesList = [
    {name: ["Afghanistan", "AF", "AFG"]},
    {name: ["Albania", "AL", "ALB"]},
    {name: ["Algeria", "DZ", "DZA"]},
    {name: ["American Samoa", "AS", "ASM"]},
    {name: ["Andorra", "AD", "AND"]},
    {name: ["Angola", "AO", "AGO"]},
    {name: ["Anguilla", "AI", "AIA"]},
    {name: ["Antarctica", "AQ", "ATA"]},
    {name: ["Antigua and Barbuda", "AG", "ATG"]},
    {name: ["Argentina", "AR", "ARG"]},
    {name: ["Armenia", "AM", "ARM"]},
    {name: ["Aruba", "AW", "ABW"]},
    {name: ["Australia", "AU", "AUS"]},
    {name: ["Austria", "AT", "AUT"]},
    {name: ["Azerbaijan", "AZ", "AZE"]},
    {name: ["Bahamas", "BS", "BHS"]},
    {name: ["Bahrain", "BH", "BHR"]},
    {name: ["Bangladesh", "BD", "BGD"]},
    {name: ["Barbados", "BB", "BRB"]},
    {name: ["Belarus", "BY", "BLR"]},
    {name: ["Belgium", "BE", "BEL"]},
    {name: ["Belize", "BZ", "BLZ"]},
    {name: ["Benin", "BJ", "BEN"]},
    {name: ["Bermuda", "BM", "BMU"]},
    {name: ["Bhutan", "BT", "BTN"]},
    {name: ["Bolivia", "BO", "BOL"]},
    {name: ["Bonaire, Sint Eustatius and Saba", "BQ", "BES"]},
    {name: ["Bosnia and Herzegovina", "BA", "BIH"]},
    {name: ["Botswana", "BW", "BWA"]},
    {name: ["Bouvet Island", "BV", "BVT"]},
    {name: ["Brazil", "BR", "BRA"]},
    {name: ["Botswana", "BW", "BWA"]},
    {name: ["British Indian Ocean Territory", "IO", "IOT"]},
    {name: ["Brunei Darussalam", "BN", "BRN"]},
    {name: ["Bulgaria", "BG", "BGR"]},
    {name: ["Burkina Faso", "BF", "BFA"]},
    {name: ["Burundi", "BI", "BDI"]},
    {name: ["Cabo Verde", "CV", "CPV"]},
    {name: ["Cambodia", "KH", "KHM"]},
    {name: ["Cameroon", "CM", "CMR"]},
    {name: ["Canada", "CA", "CAN"]},
    {name: ["Cayman Islands", "KY", "CYM"]},
    {name: ["Central African Republic", "CF", "CAF"]},
    {name: ["Chad", "TD", "TCD"]},
    {name: ["Chile", "CL", "CHL"]},
    {name: ["China", "CN", "CHN"]},
    {name: ["Christmas Island", "CX", "CXR"]},
    {name: ["Cocos Islands", "CC", "CCK"]},
    {name: ["Colombia", "CO", "COL"]},
    {name: ["Comoros", "KM", "COM"]},
    {name: ["Democratic Republic of Congo", "CD", "COD"]},
    {name: ["Congo", "CG", "COG"]},
    {name: ["Cook Islands", "CK", "COK"]},
    {name: ["Costa Rica", "CR", "CRI"]},
    {name: ["Croatia", "HR", "HRV"]},
    {name: ["Cuba", "CU", "CUB"]},
    {name: ["Botswana", "BW", "BWA"]},
    {name: ["Cuba", "CU", "CUB"]},
    {name: ["Curaçao", "CW", "CUW"]},
    {name: ["Cyprus", "CY", "CYP"]},
    {name: ["Czechia", "CZ", "CZE"]},
    {name: ["Côte d'Ivoire", "CI", "CIV"]},
    {name: ["Denmark", "DK", "DNK"]},
    {name: ["Djibouti",	"DJ", "DJI"]},
    {name: ["Dominica", "DM", "DMA"]},
    {name: ["Dominican Republic", "DO", "DOM"]},
    {name: ["Ecuador", "EC", "ECU"]},
    {name: ["Egypt", "EG", "EGY"]},
    {name: ["El Salvador", "SV", "SLV"]},
    {name: ["Equatorial Guinea", "GQ", "GNQ"]},
    {name: ["Eritrea", "ER", "ERI"]},
    {name: ["Estonia", "EE","EST"]},
    {name: ["Eswatini", "SZ", "SWZ"]},
    {name: ["Ethiopia",	"ET", "ETH"]},
    {name: ["Falkland Islands",	"FK", "FLK"]},
    {name: ["Faroe Islands", "FO", "FRO"]},
    {name: ["Fiji", "FJ", "FJI"]},
    {name: ["Finland", "FI",	"FIN"]},
    {name: ["France", "FR",	"FRA"]},
    {name: ["French Guiana", "GF", "GUF"]},
    {name: ["French Polynesia",	"PF", "PYF"]},
    {name: ["French Southern Territories", "TF", "ATF"]},
    {name: ["Gabon", "GA", "GAB"]},
    {name: ["Gambia", "GM", "GMB"]},
    {name: ["Georgia", "GE", "GEO"]},
    {name: ["Germany", "DE", "DEU"]},
    {name: ["Ghana", "GH", "GHA"]},
    {name: ["Gibraltar", "GI", "GIB	"]},
    {name: ["Greece", "GR",	"GRC"]},
    {name: ["Greenland", "GL", "GRL"]},
    {name: ["Grenada", "GD", "GRD"]},
    {name: ["Guadeloupe", "GP", "GLP"]},
    {name: ["Guam", "GU", "GUM"]},
    {name: ["Guatemala", "GT", "GTM"]},
    {name: ["Guernsey", "GG", "GGY"]},
    {name: ["Guinea", "GN", "GIN"]},
    {name: ["Guinea-Bissau", "GW", "GNB"]},
    {name: ["Guyana", "GY", "GUY"]},
    {name: ["Haiti", "HT", "HTI"]},
    {name: ["Heard Island and McDonald Islands", "HM", "HMD"]},
    {name: ["Holy See",	"VA", "VAT"]},
    {name: ["Honduras", "HN", "HND"]},
    {name: ["Hong Kong", "HK", "HKG"]},
    {name: ["Hungary", "HU", "HUN"]},
    {name: ["Iceland", "IS", "ISL"]},
    {name: ["India", "IN", "IND"]},
    {name: ["Indonesia", "ID", "IDN"]},
    {name: ["Iran", "IR", "IRN"]},
    {name: ["Iraq", "IQ", "IRQ"]},
    {name: ["Ireland", "IE", "IRL"]},
    {name: ["Isle of Man", "IM", "IMN"]},
    {name: ["Israel", "IL", "ISR"]},
    {name: ["Italy", "IT", "ITA"]},
    {name: ["Jamaica",	"JM", "JAM"]},
    {name: ["Japan", "JP", "JPN"]},
    {name: ["Jersey", "JE",	"JEY"]},
    {name: ["Jordan", "JO", "JOR"]},
    {name: ["Kazakhstan", "KZ", "KAZ"]},
    {name: ["Kenya", "KE", "KEN"]},
    {name: ["Kiribati",	"KI", "KIR"]},
    {name: ["North Korea",	"KP", "PRK"]},
    {name: ["South Korea",	"KR", "KOR"]},
    {name: ["Kuwait", "KW", "KWT"]},
    {name: ["Kyrgyzstan", "KG", "KGZ"]},
    {name: ["Lao People's Democratic Republic",	"LA", "LAO"]},
    {name: ["Latvia", "LV", "LVA"]},
    {name: ["Lebanon", "LB", "LBN"]},
    {name: ["Lesotho", "LS", "LSO"]},
    {name: ["Liberia", "LR", "LBR"]},
    {name: ["Libya", "LY", "LBY"]},
    {name: ["Liechtenstein", "LI", "LIE"]},
    {name: ["Lithuania", "LT", "LTU"]},
    {name: ["Luxembourg", "LU",	"LUX"]},
    {name: ["Macao", "MO", "MAC"]},
    {name: ["Madagascar", "MG", "MDG"]},
    {name: ["Malawi", "MW", "MWI"]},
    {name: ["Malaysia",	"MY", "MYS"]},
    {name: ["Maldives", "MV", "MDV"]},
    {name: ["Mali", "ML", "MLI"]},
    {name: ["Malta", "MT", "MLT"]},
    {name: ["Marshall Islands",	"MH", "MHL"]},
    {name: ["Martinique", "MQ", "MTQ"]},
    {name: ["Mauritania", "MR", "MRT"]},
    {name: ["Mauritius", "MU", "MUS"]},
    {name: ["Mayotte", "YT", "MYT"]},
    {name: ["Mexico", "MX", "MEX"]},
    {name: ["Micronesia", "FM", "FSM"]},
    {name: ["Moldova", "MD", "MDA"]},
    {name: ["Monaco", "MC", "MCO"]},
    {name: ["Mongolia", "MN", "MNG"]},
    {name: ["Montenegro", "ME", "MNE"]},
    {name: ["Montserrat", "MS", "MSR"]},
    {name: ["Morocco", "MA", "MAR"]},
    {name: ["Mozambique", "MZ", "MOZ"]},
    {name: ["Myanmar", "MM", "MMR"]},
    {name: ["Namibia", "NA", "NAM"]},
    {name: ["Nauru", "NR", "NRU"]},
    {name: ["Nepal", "NP", "NPL"]},
    {name: ["Netherlands", "NL", "NLD"]},
    {name: ["New Caledonia", "NC", "NCL"]},
    {name: ["New Zealand", "NZ", "NZL"]},
    {name: ["Nicaragua", "NI", "NIC"]},
    {name: ["Niger", "NE", "NER"]},
    {name: ["Nigeria", "NG", "NGA"]},
    {name: ["Niue", "NU", "NIU"]},
    {name: ["Norfolk Island", "NF", "NFK"]},
    {name: ["Northern Mariana Islands",	"MP", "MNP"]},
    {name: ["Norway", "NO", "NOR"]},
    {name: ["Oman", "OM", "OMN"]},
    {name: ["Pakistan", "PK", "PAK"]},
    {name: ["Palau", "PW", "PLW"]},
    {name: ["Palestine", "PS", "PSE"]},
    {name: ["Panama", "PA", "PAN"]},
    {name: ["Papua New Guinea",	"PG", "PNG"]},
    {name: ["Paraguay",	"PY", "PRY"]},
    {name: ["Peru", "PE", "PER"]},
    {name: ["Philippines", "PH", "PHL"]},
    {name: ["Pitcairn", "PN", "PCN"]},
    {name: ["Poland", "PL", "POL"]},
    {name: ["Portugal", "PT", "PRT"]},
    {name: ["Puerto Rico", "PR", "PRI"]},
    {name: ["Qatar", "QA", "QAT"]},
    {name: ["Republic of North Macedonia", "MK", "MKD"]},
    {name: ["Romania", "RO", "ROU"]},
    {name: ["Russian", 	"RU", "RUS"]},
    {name: ["Rwanda", "RW", "RWA"]},
    {name: ["Réunion",	"RE", "REU"]},
    {name: ["Saint Barthélemy",	"BL", "BLM"]},
    {name: ["Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN"]},
    {name: ["Saint Kitts and Nevis",  "KN", "KNA"]},
    {name: ["Saint Lucia", "LC", "LCA"]},
    {name: ["Saint Martin", "MF", "MAF"]},
    {name: ["Saint Pierre and Miquelon", "PM", "SPM"]},
    {name: ["Saint Vincent and the Grenadines", "VC", "VCT"]},
    {name: ["Samoa", "WS", "WSM"]},
    {name: ["San Marino",	"SM", 	"SMR"]},
    {name: ["Sao Tome and Principe", "ST", "STP"]},
    {name: ["Saudi Arabia", "SA", "SAU"]},
    {name: ["Senegal", "SN", "SEN"]},
    {name: ["Serbia", "RS", "SRB"]},
    {name: ["Seychelles", "SC", "SYC"]},
    {name: ["Sierra Leone",	"SL", "SLE"]},
    {name: ["Singapore", "SG", "SGP"]},
    {name: ["Sint Maarten",	"SX", "SXM"]},
    {name: ["Slovakia", "SK", "SVK"]},
    {name: ["Slovenia",	"SI", "SVN"]},
    {name: ["Solomon Islands", "SB", "SLB"]},
    {name: ["Somalia", "SO", "SOM"]},
    {name: ["South Africa", "ZA", "ZAF"]},
    {name: ["South Georgia and the South Sandwich Islands",	"GS", "SGS"]},
    {name: ["South Sudan", "SS", "SSD"]},
    {name: ["Spain", "ES", "ESP"]},
    {name: ["Sri Lanka", "LK", "LKA"]},
    {name: ["Sudan", "SD", "SDN"]},
    {name: ["Suriname", "SR", "SUR"]},
    {name: ["Svalbard and Jan Mayen", "SJ", "SJM"]},
    {name: ["Sweden", "SE", "SWE"]},
    {name: ["Switzerland", "CH", "CHE"]},
    {name: ["Syria",	"SY", "SYR"]},
    {name: ["Taiwan", "TW", "TWN"]},
    {name: ["Tajikistan", "TJ", "TJK"]},
    {name: ["Tanzania",	"TZ", "TZA"]},
    {name: ["Thailand",	"TH", "THA"]},
    {name: ["Timor-Leste", 	"TL", "TLS"]},
    {name: ["Togo", "TG", "TGO"]},
    {name: ["Tokelau", "TK", "TKL"]},
    {name: ["Tonga", "TO", "TON"]},
    {name: ["Trinidad and Tobago", "TT", "TTO"]},
    {name: ["Tunisia", "TN", "TUN"]},
    {name: ["Turkey", "TR", "TUR"]},
    {name: ["Turkmenistan",	"TM", "TKM"]},
    {name: ["Turks and Caicos Islands",	"TC", "TCA"]},
    {name: ["Tuvalu", "TV", "TUV"]},
    {name: ["Uganda",	"UG", "UGA"]},
    {name: ["Ukraine", "UA", "UKR"]},
    {name: ["United Arab Emirates", "AE", "ARE"]},
    {name: ["United Kingdom of Great Britain and Northern Ireland", "UK", "United Kingdom","GB", "GBR"]},
    {name: ["United States Minor Outlying Islands",	"UM", "UMI"]},
    {name: ["United States of America", "US", "USA", "United States"]},
    {name: ["Uruguay", "UY", "URY"]},
    {name: ["Uzbekistan", "UZ", "UZB"]},
    {name: ["Vanuatu",	"VU", "VUT"]},
    {name: ["Venezuela", "Bolivarian Republic of Venzuela",	"VE", "VEN"]},
    {name: ["Viet Nam", "Vietnam", "VN", "VNM"]},
    {name: ["Virgin Islands (British)", "British Virgin Islands", "VG", "VGB"]},
    {name: ["Virgin Islands (U.S.)", "US Virgin Islands", "VI", "VIR"]},
    {name: ["Wallis and Futuna", "WF", "WLF"]},
    {name: ["Western Sahara", "EH", "ESH"]},
    {name: ["Yemen", "YE", "YEM"]},
    {name: ["Zambia", "ZM", "ZMB"]},
    {name: ["Zimbabwe", "ZW", "ZWE"]},
    {name: ["Åland Islands", "AX", "ALA"]}

]




function capitalizeFirstLetters(sentence) {
    let words = sentence.split(" "); 
    for (let i = 0; i < words.length; i++) {
        words[i] = words[i].charAt(0).toUpperCase() + words[i].slice(1);
    }
    
    let capitalizedSentence = words.join(" ");
    
    return capitalizedSentence;
}





function checkCountryValidity(countryToCheck){
    const validCountry = countriesList.some(country => country.name.includes(capitalizeFirstLetters(countryToCheck)))
    return validCountry
}


function countryList(){
    return countriesList
}


module.exports = {
    checkCountryValidity,
    countryList
}